### ISSUE TITLE
NameError when running application 

### ISSUE THREAD

**Issue by d7e7r7** [code-developers/FB-Tool#1]
I get the following errors when trying to run the application... 

Traceback (most recent call last):
  File "fbtool.py", line 2534, in <module>
    tool_main_function()
  File "fbtool.py", line 79, in tool_main_function
    print logo
NameError: global name 'logo' is not defined

**Comment by krishpranav** [comment]
I have fixed it just try it by running this commands

if you already cloned this repo:
```
git pull
python fbtool.py
```

clone:
```
git clone https://github.com/code-developers/fbtool
cd fbtool
python fbtool.py
```
